gob:
  mode: development
  log_level: INFO

services:
  general-operations-bots:
    enabled: true
    port: 50001
    config_path: ./general-operations-bots/tmp/settings.json
    start_command: "python3 /home/ds/sambashare/GOB/GOB-system/general-operations-bots/run_ui.py"

  grid-overwatch-bridge:
    enabled: true
    port: 8051
    state_path: ./grid-overwatch-bridge/state
    start_command: "python3 /home/ds/sambashare/GOB/GOB-system/grid-overwatch-bridge/service.py"

  frontend:
    enabled: true
    port: 3000
    build_path: ./frontend/build
    start_command: "npm start --prefix /home/ds/sambashare/GOB/GOB-system/frontend"

  gob-controller:
    enabled: true
    port: 8080
    api_prefix: /api/system
    start_command: "python3 /home/ds/sambashare/GOB/GOB-system/gob-controller/controller.py"

networking:
  reverse_proxy: nginx
  ssl_enabled: false

monitoring:
  health_check_interval: 30
  log_retention_days: 7
  metrics_enabled: true