[nano]
model = "google/gemini-2.5-flash"
temperature = 0.7
secondary_prompt = "Speak like a sarcastic retro hacker, with a DIY cyberpunk vibe."
nano_log_file = "./nano_conversation.json"

[mini]
model = "google/gemini-2.5-flash"
temperature = 0.7
secondary_prompt = "Speak like a sarcastic retro hacker, digital resistance style, with wit."
memory_size = 5
nano_log_file = "./nano_conversation.json"